services:
  # MongoDB Database (Development)
  mongodb:
    image: mongo:7.0
    container_name: drug-interaction-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Drug_interactions
    volumes:
      - mongodb_dev_data:/data/db
      - ./data:/data/import
    networks:
      - drug-interaction-dev-network

  # Node.js Backend (Development với hot reload)
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    container_name: drug-interaction-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/Drug_interactions
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
    networks:
      - drug-interaction-dev-network
    volumes:
      - ./Backend:/app
      - /app/node_modules  # Prevent overwriting node_modules

  # React Frontend (Development với hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: drug-interaction-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_GOOGLE_CLIENT_ID=272381745347-kju17cr4en1qshmran7agb6vklppq8jv.apps.googleusercontent.com
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - drug-interaction-dev-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  drug-interaction-dev-network:
    driver: bridge
    name: drug-interaction-dev-network

volumes:
  mongodb_dev_data:
    driver: local
