services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: drug-interaction-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Drug_interactions
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
      - ./data:/data/import  # Để import dữ liệu từ thư mục data
    networks:
      - drug-interaction-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Node.js Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: drug-interaction-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_CONNECTION_STRING=mongodb://admin:password123@mongodb:27017/Drug_interactions?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - CORS_ORIGIN=http://localhost:3000
    env_file:
      - ./Backend/.env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - drug-interaction-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ./Backend/assets:/app/assets  # Để lưu uploaded files

  # React Frontend (Development Server - No Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: drug-interaction-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_GOOGLE_CLIENT_ID=272381745347-kju17cr4en1qshmran7agb6vklppq8jv.apps.googleusercontent.com
      - CHOKIDAR_USEPOLLING=true
      - GENERATE_SOURCEMAP=false
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - drug-interaction-network
    stdin_open: true
    tty: true

# Custom network
networks:
  drug-interaction-network:
    driver: bridge
    name: drug-interaction-network

# Volumes để persist data
volumes:
  mongodb_data:
    driver: local
